version: '3'

services:
  postgres-api:
    image: postgres:14.3
    container_name: email-verifier-database
    ports:
      - '5555:5432'
    environment:
      POSTGRES_DB: 'registration_dev'
      POSTGRES_USER: 'emailverifier'
      POSTGRES_PASSWORD: 'emailverifier'
      ADDITIONAL_POSTGRES_DBS: 'registration_test,notification_dev,notification_test'
    volumes:
      - ./databases/init-scripts:/docker-entrypoint-initdb.d
      - ./.docker-data/.pg-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: email-verifier-rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBIT_URL=amqp://guest:guest@localhost:5672/
      - DATABASE_URL=postgresql://emailverifier:emailverifier@localhost:5555/registration_dev
      - REGISTRATION_REQUEST_QUEUE=registration-request
      - REGISTRATION_REQUEST_ROUTING_KEY=42
    volumes:
      - ./.docker-data/.rabbit-data:/var/lib/rabbitmq/
      - ./.docker-data/.rabbit-log:/var/log/rabbitmq
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_consistent_hash_exchange && rabbitmq-server"